mysql:
  url: localhost
  username: root
  password: 123456
  schema: adm_videos
  port: 3306

server:
  port: 8081
  undertow:
    threads:
      worker: 10 # Generally this should be reasonably high, at least 10 per CPU core: https://undertow.io/undertow-docs/undertow-docs-2.1.0/index.html#listeners-2
      io: 2 # One I